

[build]
setup = [
  "nodejs_22, yarn-1_x"
]

[install] = [
  "npm install -g corepack@0.24.1 && corepack enable",
  "yarn install --check-cache"
]

[node:install] = [
  "npm install -g corepack@0.24.1 && corepack enable",
  "yarn install --check-cache"
]

[build] = [
  "cd .medusa/server && yarn install --omit=dev --force"
]

[start] = [
  "npm run predeploy && npm run start"
]